server:
  port: 9001
spring:
  application:
    name: customer-server
  datasource:
    url: jdbc:mysql://localhost:3306/empdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos