server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/empdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  application:
    name: order-server
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos